[tool.poetry]
name = "jsaml"
version = "0.1.0"
description = ""
authors = ["Tim Hawes <trhawes@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
nuitka = "^1.6.4"
pyyaml = "^6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
